/**
 * SAMPLE / CONCEPT case studies (not real client projects).
 * They are seeded with isSample = true so the site shows a "Sample project" badge (toggle in
 * Admin → Settings → Modules). Results are illustrative targets, not verified outcomes.
 * Replace each with a real ThetaX project in Admin → Portfolio (edit or delete in one click).
 *
 * Images are original SVG mockups generated by `npm run art:portfolio`
 * (scripts/generate-portfolio-art.mjs) into /public/portfolio/<slug>/.
 */

export const PORTFOLIO_CATEGORIES = ["AI Automation", "Digital Marketing", "UI/UX Design", "Web Development", "Graphic Design", "BPO"] as const;

export type ArtKind = "workflow" | "chat" | "dashboard" | "browser" | "mobile" | "social" | "funnel" | "brand" | "print" | "support" | "docs" | "kanban";

export type ProjectContent = {
  slug: string;
  title: string;
  client: string;
  category: (typeof PORTFOLIO_CATEGORIES)[number];
  industry: string;
  year: number;
  summary: string;
  problem: string;
  solution: string;
  description: string;
  results: { label: string; value: string }[];
  techStack: string[];
  services: string[]; // service slugs
  isFeatured: boolean;
  order: number;
  /** art direction for generated mockups: cover + 3 gallery images */
  art: { accent: string; cover: ArtKind; gallery: [ArtKind, ArtKind, ArtKind]; brand: string };
};

const concept = "<p><em>This is a concept case study created to show our approach. Metrics are illustrative targets, not reported client results.</em></p>";

export const projects: ProjectContent[] = [
  // ───────────── AI Automation (3) ─────────────
  {
    slug: "ai-invoice-processing-automation",
    title: "AI Invoice Processing Automation",
    client: "Concept — logistics company",
    category: "AI Automation",
    industry: "Logistics",
    year: 2026,
    summary: "An AI document pipeline that reads supplier invoices, matches them to purchase orders and posts approved entries to accounting — with humans reviewing only the exceptions.",
    problem: "Finance staff re-type thousands of invoices a month. It is slow, error-prone and causes late payments and duplicate entries at month-end.",
    solution: "Invoices arriving by email are classified and extracted with AI, validated against purchase orders, and pushed to the accounting system. Mismatches go to a simple review queue, and finance gets a daily summary.",
    description: `<h2>How it works</h2><ol><li>Email inbox watched by an n8n workflow</li><li>AI extracts vendor, amounts, tax and line items</li><li>Rules engine matches against open POs</li><li>Approved entries sync to accounting; exceptions go to review</li></ol>${concept}`,
    results: [
      { label: "Target reduction in manual entry", value: "80%" },
      { label: "Target processing time per invoice", value: "< 1 min" },
      { label: "Exceptions routed for human review", value: "100%" },
    ],
    techStack: ["n8n", "Claude API", "OCR", "PostgreSQL", "QuickBooks API"],
    services: ["ai-automation", "ai-services"],
    isFeatured: true,
    order: 1,
    art: { accent: "#F7941D", cover: "workflow", gallery: ["docs", "dashboard", "workflow"], brand: "LedgerFlow" },
  },
  {
    slug: "whatsapp-ai-sales-agent",
    title: "WhatsApp AI Sales Agent",
    client: "Concept — fashion retail brand",
    category: "AI Automation",
    industry: "Retail & E-commerce",
    year: 2026,
    summary: "A bilingual (English/Urdu) AI agent that answers product questions, checks stock and takes orders on WhatsApp 24/7, handing complex chats to staff.",
    problem: "Hundreds of daily WhatsApp messages mean slow replies, lost overnight orders and staff stuck answering the same questions.",
    solution: "An AI agent grounded in the live catalogue and policies answers FAQs, recommends sizes, confirms stock and creates draft orders, with one-tap human handoff.",
    description: `<h2>Agent capabilities</h2><ul><li>Product & size recommendations from the catalogue</li><li>Stock and delivery-time lookups</li><li>Order capture with payment link</li><li>Human handoff with full conversation context</li></ul>${concept}`,
    results: [
      { label: "Target share of chats resolved by AI", value: "70%" },
      { label: "Target first-response time", value: "< 10s" },
      { label: "Coverage", value: "24/7" },
    ],
    techStack: ["WhatsApp Cloud API", "Claude API", "Node.js", "Shopify API"],
    services: ["ai-services", "ai-automation"],
    isFeatured: true,
    order: 2,
    art: { accent: "#25D366", cover: "chat", gallery: ["chat", "dashboard", "workflow"], brand: "Libas" },
  },
  {
    slug: "hr-recruitment-screening-automation",
    title: "HR Recruitment Screening Automation",
    client: "Concept — growing services firm",
    category: "AI Automation",
    industry: "Professional Services",
    year: 2025,
    summary: "Automated CV intake, AI scoring against role criteria, interview scheduling and candidate updates — so recruiters spend time on people, not paperwork.",
    problem: "Each job post brings hundreds of CVs. Manual screening takes days and good candidates drop out while waiting.",
    solution: "Applications are parsed and scored against a transparent rubric, shortlisted candidates receive a booking link automatically, and every applicant gets a timely status update.",
    description: `<h2>Guardrails</h2><p>Scoring criteria are visible and editable; final decisions always stay with a human recruiter.</p>${concept}`,
    results: [
      { label: "Target time-to-shortlist", value: "1 day" },
      { label: "Applicants receiving updates", value: "100%" },
      { label: "Target recruiter hours saved / role", value: "15+" },
    ],
    techStack: ["Make", "Claude API", "Google Workspace", "Calendly"],
    services: ["ai-automation"],
    isFeatured: false,
    order: 3,
    art: { accent: "#8B5CF6", cover: "kanban", gallery: ["docs", "workflow", "dashboard"], brand: "TalentOps" },
  },

  // ───────────── Digital Marketing (3) ─────────────
  {
    slug: "real-estate-lead-generation-campaign",
    title: "Real Estate Lead Generation Campaign",
    client: "Concept — property developer, Karachi",
    category: "Digital Marketing",
    industry: "Real Estate",
    year: 2026,
    summary: "Full-funnel Meta and Google campaigns with high-converting landing pages and instant WhatsApp follow-up for every enquiry.",
    problem: "Ad spend was producing unqualified leads, and slow follow-up meant interested buyers went cold.",
    solution: "Audience-specific creatives, a fast landing page with project details and a lead form, plus automated WhatsApp and email follow-up within minutes.",
    description: `<h2>Channels</h2><ul><li>Meta lead ads + retargeting</li><li>Google Search for high-intent keywords</li><li>Landing page A/B tests</li></ul>${concept}`,
    results: [
      { label: "Target cost-per-lead improvement", value: "40%" },
      { label: "Target lead response time", value: "< 5 min" },
      { label: "Channels connected to CRM", value: "3" },
    ],
    techStack: ["Meta Ads", "Google Ads", "GA4", "Landing page", "n8n"],
    services: ["digital-marketing", "ai-automation"],
    isFeatured: true,
    order: 4,
    art: { accent: "#0EA5E9", cover: "social", gallery: ["funnel", "social", "dashboard"], brand: "Skyline Residences" },
  },
  {
    slug: "ecommerce-seo-aeo-growth",
    title: "E-commerce SEO & AEO Growth Program",
    client: "Concept — home décor store",
    category: "Digital Marketing",
    industry: "Retail & E-commerce",
    year: 2025,
    summary: "Technical SEO, product schema, buying guides and AI-answer-engine optimisation to grow organic traffic and get cited by AI search.",
    problem: "Thin product pages and no content strategy meant the store relied entirely on paid ads.",
    solution: "We fixed site speed and structure, added product and FAQ schema, and published buying guides written to answer real customer questions.",
    description: `<h2>Workstreams</h2><ul><li>Technical audit & Core Web Vitals</li><li>Schema markup at scale</li><li>Content hub with question-led guides</li></ul>${concept}`,
    results: [
      { label: "Target organic traffic growth (6 mo)", value: "2×" },
      { label: "Pages with structured data", value: "100%" },
      { label: "Buying guides published", value: "24" },
    ],
    techStack: ["Search Console", "GA4", "Schema.org", "Ahrefs", "Next.js"],
    services: ["digital-marketing", "web-development"],
    isFeatured: false,
    order: 5,
    art: { accent: "#10B981", cover: "dashboard", gallery: ["browser", "funnel", "dashboard"], brand: "Nest & Nook" },
  },
  {
    slug: "social-media-brand-launch",
    title: "Social Media Brand Launch",
    client: "Concept — specialty coffee startup",
    category: "Digital Marketing",
    industry: "Food & Beverage",
    year: 2026,
    summary: "A 90-day launch plan: content calendar, short-form video, influencer seeding and community management across Instagram and TikTok.",
    problem: "A new brand with zero audience needed awareness and footfall before opening day.",
    solution: "Consistent branded content, behind-the-scenes reels, local creator partnerships and a launch-week offer tracked end to end.",
    description: `<h2>Launch plan</h2><ol><li>Teaser phase</li><li>Opening week campaign</li><li>Community & UGC phase</li></ol>${concept}`,
    results: [
      { label: "Posts in 90-day calendar", value: "120" },
      { label: "Target follower milestone", value: "10k" },
      { label: "Creators in seeding program", value: "15" },
    ],
    techStack: ["Instagram", "TikTok", "Meta Business Suite", "Canva", "CapCut"],
    services: ["digital-marketing", "graphic-design"],
    isFeatured: false,
    order: 6,
    art: { accent: "#B45309", cover: "social", gallery: ["social", "mobile", "funnel"], brand: "Brew Lab" },
  },

  // ───────────── UI/UX Design (3) ─────────────
  {
    slug: "fintech-mobile-app-ux",
    title: "Fintech Mobile App UX",
    client: "Concept — digital wallet startup",
    category: "UI/UX Design",
    industry: "Financial Services",
    year: 2026,
    summary: "Research-led UX and a complete design system for a mobile wallet: onboarding, payments, bill-pay and spending insights.",
    problem: "Users abandoned onboarding and found sending money confusing and untrustworthy.",
    solution: "Simplified 3-step onboarding, clear payment confirmations, accessible colour and type, and a reusable component library.",
    description: `<h2>Deliverables</h2><ul><li>User interviews & journey maps</li><li>Clickable Figma prototype</li><li>Design system with 80+ components</li></ul>${concept}`,
    results: [
      { label: "Onboarding steps", value: "8 → 3" },
      { label: "Design system components", value: "80+" },
      { label: "Usability test sessions", value: "12" },
    ],
    techStack: ["Figma", "FigJam", "Maze", "Design tokens"],
    services: ["ui-ux-design"],
    isFeatured: true,
    order: 7,
    art: { accent: "#6366F1", cover: "mobile", gallery: ["mobile", "mobile", "brand"], brand: "Paysa" },
  },
  {
    slug: "saas-analytics-dashboard-redesign",
    title: "SaaS Analytics Dashboard Redesign",
    client: "Concept — B2B analytics platform",
    category: "UI/UX Design",
    industry: "Software / SaaS",
    year: 2025,
    summary: "A dashboard redesign that turns dense data into clear, actionable insight with better hierarchy, filtering and dark mode.",
    problem: "Customers struggled to find key metrics; support tickets about 'where is…' were rising.",
    solution: "Information architecture rebuilt around tasks, a modular widget grid, consistent charts, and saved views.",
    description: `<h2>Approach</h2><p>Heuristic audit, analytics review, card sorting with real users, then iterative prototypes.</p>${concept}`,
    results: [
      { label: "Navigation depth", value: "4 → 2" },
      { label: "Reusable chart patterns", value: "12" },
      { label: "Themes", value: "Light + Dark" },
    ],
    techStack: ["Figma", "Hotjar", "Storybook", "Tailwind CSS"],
    services: ["ui-ux-design", "web-development"],
    isFeatured: false,
    order: 8,
    art: { accent: "#F7941D", cover: "dashboard", gallery: ["dashboard", "kanban", "brand"], brand: "Metricly" },
  },
  {
    slug: "healthcare-booking-app-ux",
    title: "Healthcare Appointment Booking UX",
    client: "Concept — multi-clinic healthcare group",
    category: "UI/UX Design",
    industry: "Healthcare",
    year: 2026,
    summary: "An accessible booking experience for web and mobile: find a doctor, pick a slot, get reminders and manage visits.",
    problem: "Phone-only booking caused long hold times and many no-shows.",
    solution: "A WCAG-aware booking flow with large tap targets, Urdu/English content, smart reminders and easy rescheduling.",
    description: `<h2>Accessibility first</h2><p>Designed for older patients and low-bandwidth connections, tested with real patients.</p>${concept}`,
    results: [
      { label: "Steps to book", value: "3" },
      { label: "Languages", value: "EN + UR" },
      { label: "Accessibility target", value: "WCAG AA" },
    ],
    techStack: ["Figma", "Prototyping", "Accessibility audit"],
    services: ["ui-ux-design"],
    isFeatured: false,
    order: 9,
    art: { accent: "#14B8A6", cover: "mobile", gallery: ["mobile", "browser", "dashboard"], brand: "CareSlot" },
  },

  // ───────────── Web Development (2) ─────────────
  {
    slug: "corporate-website-real-estate",
    title: "Corporate Website for a Real Estate Developer",
    client: "Concept — real estate developer",
    category: "Web Development",
    industry: "Real Estate",
    year: 2026,
    summary: "A premium, animated Next.js website with project listings, floor plans, WhatsApp lead capture and an easy admin dashboard.",
    problem: "An outdated, slow website ranked poorly on mobile and produced almost no enquiries.",
    solution: "A fast, SEO-ready site with immersive project pages, structured data, a CMS and lead routing to the sales team.",
    description: `<h2>Built with</h2><p>Next.js, a headless content model, image optimisation and full technical SEO.</p>${concept}`,
    results: [
      { label: "Lighthouse target", value: "90+" },
      { label: "Project pages", value: "12" },
      { label: "Lead channels", value: "Form + WhatsApp" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "MySQL"],
    services: ["web-development", "ui-ux-design"],
    isFeatured: true,
    order: 10,
    art: { accent: "#F7941D", cover: "browser", gallery: ["browser", "mobile", "dashboard"], brand: "Horizon Estates" },
  },
  {
    slug: "b2b-ecommerce-portal",
    title: "B2B Wholesale E-commerce Portal",
    client: "Concept — industrial supplies distributor",
    category: "Web Development",
    industry: "Manufacturing & Distribution",
    year: 2025,
    summary: "A wholesale ordering portal with customer-specific pricing, bulk ordering, credit limits and ERP sync.",
    problem: "Orders arrived by phone and email, causing errors, delays and no visibility for customers.",
    solution: "A secure portal where buyers see their price lists, re-order in seconds and track deliveries — synced with inventory.",
    description: `<h2>Features</h2><ul><li>Tiered pricing & quotes</li><li>Bulk CSV ordering</li><li>Order tracking & invoices</li></ul>${concept}`,
    results: [
      { label: "SKUs in catalogue", value: "5,000+" },
      { label: "Order channels unified", value: "3 → 1" },
      { label: "Integration", value: "ERP sync" },
    ],
    techStack: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "REST APIs"],
    services: ["web-development"],
    isFeatured: false,
    order: 11,
    art: { accent: "#3B82F6", cover: "browser", gallery: ["dashboard", "browser", "kanban"], brand: "BulkMart" },
  },

  // ───────────── Graphic Design (2) ─────────────
  {
    slug: "brand-identity-tech-startup",
    title: "Brand Identity for a Tech Startup",
    client: "Concept — logistics tech startup",
    category: "Graphic Design",
    industry: "Technology",
    year: 2026,
    summary: "Logo, colour system, typography, iconography and brand guidelines for a startup preparing to raise funding.",
    problem: "An inconsistent DIY look undermined credibility with investors and enterprise customers.",
    solution: "A distinctive identity system with clear guidelines and ready-to-use templates for decks, social and documents.",
    description: `<h2>Identity system</h2><ul><li>Primary & secondary marks</li><li>Colour & type system</li><li>Pitch deck & social templates</li></ul>${concept}`,
    results: [
      { label: "Brand assets delivered", value: "60+" },
      { label: "Guideline pages", value: "32" },
      { label: "Template formats", value: "8" },
    ],
    techStack: ["Adobe Illustrator", "Figma", "After Effects"],
    services: ["graphic-design"],
    isFeatured: false,
    order: 12,
    art: { accent: "#EC4899", cover: "brand", gallery: ["brand", "print", "social"], brand: "Routify" },
  },
  {
    slug: "packaging-print-design-food-brand",
    title: "Packaging & Print Design for a Food Brand",
    client: "Concept — organic snacks brand",
    category: "Graphic Design",
    industry: "Food & Beverage",
    year: 2025,
    summary: "Shelf-ready packaging, catalogue and point-of-sale materials designed to stand out in supermarkets.",
    problem: "Generic packaging got lost on crowded shelves and didn't communicate the brand's natural ingredients.",
    solution: "A bold, ingredient-led packaging system with a flexible colour code per flavour, plus matching print collateral.",
    description: `<h2>Range</h2><p>Six flavour variants, a product catalogue and in-store display units.</p>${concept}`,
    results: [
      { label: "Flavour variants designed", value: "6" },
      { label: "Print pieces", value: "14" },
      { label: "Print-ready files", value: "CMYK" },
    ],
    techStack: ["Adobe Illustrator", "Photoshop", "InDesign"],
    services: ["graphic-design"],
    isFeatured: false,
    order: 13,
    art: { accent: "#84CC16", cover: "print", gallery: ["print", "brand", "social"], brand: "Crunchly" },
  },

  // ───────────── BPO (1) ─────────────
  {
    slug: "customer-support-bpo-team",
    title: "24/7 Customer Support BPO Team",
    client: "Concept — UK SaaS company",
    category: "BPO",
    industry: "Software / SaaS",
    year: 2026,
    summary: "A dedicated Karachi-based support team covering email and live chat around the clock, with AI-drafted replies and weekly QA reporting.",
    problem: "A fast-growing SaaS company couldn't hire support staff quickly enough; response times were slipping.",
    solution: "We recruit and train a dedicated team on the product and helpdesk, add AI reply assistance and a QA scorecard, and report KPIs weekly.",
    description: `<h2>Operating model</h2><ul><li>Shifts aligned to UK hours + overnight cover</li><li>Daily QA sampling</li><li>Weekly KPI review</li></ul>${concept}`,
    results: [
      { label: "Coverage", value: "24/7" },
      { label: "Target first response", value: "< 1 hr" },
      { label: "QA-reviewed tickets / week", value: "10%" },
    ],
    techStack: ["Zendesk", "Intercom", "AI reply assist", "Looker Studio"],
    services: ["bpo-services", "ai-services"],
    isFeatured: true,
    order: 14,
    art: { accent: "#F7941D", cover: "support", gallery: ["support", "dashboard", "kanban"], brand: "HelpDesk Pro" },
  },
];

export function projectImages(slug: string) {
  return { cover: `/portfolio/${slug}/cover.svg`, gallery: [1, 2, 3].map((n) => `/portfolio/${slug}/${n}.svg`) };
}
